language: generic

jobs:
  include:
  - stage: Continuous Integration
    name: SwiftPM macOS
    os: osx
    osx_image: xcode10.3
    script:
    - swift test --parallel
  - stage: Continuous Integration
    name: SwiftPM Linux
    os: Linux
    dist: trusty
    sudo: required
    install:
    - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
    - swiftenv install 4.2
    - swiftenv local 4.2
    - swift --version
    script:
    - swift test --parallel
  - stage: Continuous Integration
    name: Code Coverage (Xcode 10.3)
    os: osx
    osx_image: xcode10.3
    script:
    - swift package generate-xcodeproj --enable-code-coverage
    - xcodebuild -scheme SourceDocs-Package test
    after_success:
    - bash <(curl -s https://codecov.io/bash) -J 'SourceDocs'
  - stage: Continuous Integration
    name: Installation with Homebrew (macOS)
    os: osx
    osx_image: xcode10.3
    script:
    - brew update
    - brew install sourcedocs
    - sourcedocs version
  - stage: Continuous Integration
    name: Installation from Source (macOS)
    os: osx
    osx_image: xcode10.3
    script:
    - git clone --depth 1 https://github.com/eneko/SourceDocs.git
    - cd SourceDocs
    - make install
    - sourcedocs version
